#############################################################################
# Makefile for building: Faina
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  Faina.pro
# Template: app
# Command: make -o Makefile Faina.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. 
QMAKE         = 
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Faina1.0.0
DISTDIR = /home/vadim/Faina/.tmp/Faina1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -fopenmp   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Src/KPIevaluator.cpp \
		Src/bremsstrahlung.cpp \
		Src/coordinateTransform.cpp \
		Src/examples.cpp \
		Src/inverseCompton.cpp \
		Src/massiveParticleDistribution.cpp \
		Src/optimization.cpp \
		Src/photonDistribution.cpp \
		Src/pionDecay.cpp \
		Src/radiation.cpp \
		Src/radiationSource.cpp \
		Src/radiationSourceFactory.cpp \
		Src/synchrotron.cpp \
		Src/util.cpp 
OBJECTS       = KPIevaluator.o \
		bremsstrahlung.o \
		coordinateTransform.o \
		examples.o \
		inverseCompton.o \
		main.o \
		massiveParticleDistribution.o \
		optimization.o \
		photonDistribution.o \
		pionDecay.o \
		radiation.o \
		radiationSource.o \
		radiationSourceFactory.o \
		synchrotron.o \
		util.o
DIST          = Src/KPIevaluator.h \
		Src/bremsstrahlung.h \
		Src/constants.h \
		Src/coordinateTransform.h \
		Src/examples.h \
		Src/inverseCompton.h \
		Src/massiveParticleDistribution.h \
		Src/optimization.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/pionDecay.h \
		Src/radiation.h \
		Src/radiationSource.h \
		Src/radiationSourceFactory.h \
		Src/synchrotron.h \
		Src/util.h Src/KPIevaluator.cpp \
		Src/bremsstrahlung.cpp \
		Src/coordinateTransform.cpp \
		Src/examples.cpp \
		Src/inverseCompton.cpp \
		main.cpp \
		Src/massiveParticleDistribution.cpp \
		Src/optimization.cpp \
		Src/photonDistribution.cpp \
		Src/pionDecay.cpp \
		Src/radiation.cpp \
		Src/radiationSource.cpp \
		Src/radiationSourceFactory.cpp \
		Src/synchrotron.cpp \
		Src/util.cpp
QMAKE_TARGET  = Faina
DESTDIR       = 
TARGET        = Faina


first: all
####### Build rules

Faina:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Faina.pro 		Faina.pro
	$(QMAKE) -o Makefile Faina.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Faina.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Faina.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Faina

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

KPIevaluator.o: Src/KPIevaluator.cpp Src/util.h \
		Src/constants.h \
		Src/radiationSource.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/radiation.h \
		Src/photonDistribution.h \
		Src/KPIevaluator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KPIevaluator.o Src/KPIevaluator.cpp

bremsstrahlung.o: Src/bremsstrahlung.cpp Src/constants.h \
		Src/util.h \
		Src/coordinateTransform.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/bremsstrahlung.h \
		Src/radiationSource.h \
		Src/radiation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bremsstrahlung.o Src/bremsstrahlung.cpp

coordinateTransform.o: Src/coordinateTransform.cpp Src/constants.h \
		Src/util.h \
		Src/coordinateTransform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coordinateTransform.o Src/coordinateTransform.cpp

examples.o: Src/examples.cpp Src/constants.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/util.h \
		Src/inverseCompton.h \
		Src/radiationSource.h \
		Src/radiation.h \
		Src/synchrotron.h \
		Src/optimization.h \
		Src/KPIevaluator.h \
		Src/pionDecay.h \
		Src/bremsstrahlung.h \
		Src/radiationSourceFactory.h \
		Src/coordinateTransform.h \
		Src/examples.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o examples.o Src/examples.cpp

inverseCompton.o: Src/inverseCompton.cpp Src/constants.h \
		Src/util.h \
		Src/coordinateTransform.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/inverseCompton.h \
		Src/radiationSource.h \
		Src/radiation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inverseCompton.o Src/inverseCompton.cpp

main.o: main.cpp Src/constants.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/util.h \
		Src/inverseCompton.h \
		Src/radiationSource.h \
		Src/radiation.h \
		Src/synchrotron.h \
		Src/optimization.h \
		Src/KPIevaluator.h \
		Src/pionDecay.h \
		Src/bremsstrahlung.h \
		Src/coordinateTransform.h \
		Src/radiationSourceFactory.h \
		Src/examples.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

massiveParticleDistribution.o: Src/massiveParticleDistribution.cpp Src/constants.h \
		Src/util.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o massiveParticleDistribution.o Src/massiveParticleDistribution.cpp

optimization.o: Src/optimization.cpp Src/util.h \
		Src/constants.h \
		Src/radiationSource.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/synchrotron.h \
		Src/radiation.h \
		Src/inverseCompton.h \
		Src/optimization.h \
		Src/KPIevaluator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optimization.o Src/optimization.cpp

photonDistribution.o: Src/photonDistribution.cpp Src/constants.h \
		Src/util.h \
		Src/photonDistribution.h \
		Src/particleDistribution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o photonDistribution.o Src/photonDistribution.cpp

pionDecay.o: Src/pionDecay.cpp Src/constants.h \
		Src/util.h \
		Src/coordinateTransform.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/pionDecay.h \
		Src/radiationSource.h \
		Src/radiation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pionDecay.o Src/pionDecay.cpp

radiation.o: Src/radiation.cpp Src/constants.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/photonDistribution.h \
		Src/radiationSource.h \
		Src/radiation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radiation.o Src/radiation.cpp

radiationSource.o: Src/radiationSource.cpp Src/constants.h \
		Src/util.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/radiationSource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radiationSource.o Src/radiationSource.cpp

radiationSourceFactory.o: Src/radiationSourceFactory.cpp Src/constants.h \
		Src/radiationSource.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/util.h \
		Src/radiationSourceFactory.h \
		Src/radiation.h \
		Src/photonDistribution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radiationSourceFactory.o Src/radiationSourceFactory.cpp

synchrotron.o: Src/synchrotron.cpp Src/constants.h \
		Src/util.h \
		Src/massiveParticleDistribution.h \
		Src/particleDistribution.h \
		Src/synchrotron.h \
		Src/radiationSource.h \
		Src/radiation.h \
		Src/photonDistribution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o synchrotron.o Src/synchrotron.cpp

util.o: Src/util.cpp Src/constants.h \
		Src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o Src/util.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

